#!/usr/bin/env python
# -*- coding: utf-8 -*-

DOCUMENTATION = '''
---
module: hipchat
short_description: Send notification to hipchat
description:
   - Send notification to hipchat
options:
  token:
    description:
      - API token
    required: true
    default: null
  room:
    description:
      - room id
    required: true
    default: null
  from:
    description:
      - from
    required: false
    default: ansible
  msg:
    description:
      - msg
    required: true
    default: null
  color:
    description:
      - msg color
    required: false
    default: yellow
    choices: ["yellow", "red", "green", "purple", "gray", "random"]
  msg_format:
    description:
      - msg format
    required: false
    default: text
    choices: ["text", "html"]
  notify:
    descriptino:
      - notify or not (change the tab color, play a sound, etc)
    required: false
    default: true
    choces: ["true", "false"]
notes:
   This is just a Proof of Concept code.

requirements: null
author: Shirou WAKAYAMA
'''

EXAMPLES = '''
- action: hipchat token=AAAAAA room=notify msg=\"Ansible task finished\"
'''

# ===========================================
# HipChat module specific support methods.
#

import urllib2
import urllib

MSG_URI="https://api.hipchat.com/v1/rooms/message?"

def send_msg(token, room, msg_from, msg, msg_format='text',
             color='yellow', notify=False):
    params = {}
    params['room_id'] = room
    params['from'] = msg_from[:15]
    params['message'] = msg
    params['message_format'] = msg_format
    params['color'] = color

    if notify:
        params['notify'] = 1
    else:
        params['notify'] = 0

    url = MSG_URI + "auth_token=%s" % (token)
    response = urllib2.urlopen(url, urllib.urlencode(params))
    return response.read()


# ===========================================
# Module execution.
#

def main():
    module = AnsibleModule(
        argument_spec=dict(
            token=dict(required=True),
            room=dict(required=True),
            msg=dict(required=True),
            msg_from=dict(default="Ansible"),
            color=dict(default="yellow", choices=["yellow", "red", "green",
                                                  "purple", "gray", "random"]),
            msg_format=dict(default="text", choices=["text", "html"]),
            notify=dict(default=True, choices=BOOLEANS),
        ),
        supports_check_mode=True
    )

    token = module.params["token"]
    room = module.params["room"]
    msg = module.params["msg"]
    msg_from = module.params["msg_from"]
    color = module.params["color"]
    msg_format = module.params["msg_format"]
    notify = module.params["notify"]

    try:
        send_msg(token, room, msg_from, msg, msg_format,
                 color, notify)
    except Exception, e:
        module.fail_json(msg="unable to sent msg: %s" % e)

    changed = True
    module.exit_json(changed=changed, room=room, msg_from=msg_from,
                     msg=msg)

# this is magic, see lib/ansible/module_common.py
#<<INCLUDE_ANSIBLE_MODULE_COMMON>>
main()
